ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
# FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}
FROM registry.cn-hangzhou.aliyuncs.com/qingya-private/kibana7.5.0:7.5.0

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
