ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:7.5.0
# FROM registry.cn-hangzhou.aliyuncs.com/qingya-private/elk:7.5.0
# FROM elasticsearch:7.5.0


# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
