ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
# FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
FROM elasticsearch:7.4.2


# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
