ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
# FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}
FROM registry.cn-hangzhou.aliyuncs.com/qingya-private/logstash:7.5.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
